name: enrutador
description: "A new Flutter project."
publish_to: "https://pub.dev"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  advanced_media_picker: ^0.1.2
  animated_custom_dropdown: ^3.1.1
  animated_hint_textfield: ^1.1.1
  app_links: ^7.0.0
  auto_size_text: ^3.0.0
  avatar_glow: ^3.0.1
  badges: ^3.1.2
  cunning_document_scanner: ^1.4.0
  cupertino_icons: ^1.0.8
  filesize: ^2.0.1
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_libphonenumber: ^2.7.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_map_animations: ^0.9.0
  flutter_map_compass: ^1.1.1
  flutter_map_location_marker: ^10.1.0
  flutter_map_math: ^0.2.4
  flutter_map_polywidget: ^1.0.1
  flutter_material_color_picker: ^1.2.0
  flutter_phone_direct_caller: ^2.2.1
  flutter_slider_drawer: ^3.0.2
  geocoding: ^4.0.0
  get: ^4.7.3
  http: ^1.6.0
  image: ^4.6.0
  input_quantity: ^2.5.2
  internet_connection_checker_plus: ^2.9.1
  intl: 0.20.2
  latlong2: ^0.9.1
  line_icons: ^2.0.3
  loading_animation_widget: ^1.3.0
  location: ^8.0.1
  map_launcher: ^4.4.2
  oktoast: ^3.4.0
  open_location_code: ^1.0.1
  open_route_service: ^1.2.7
  package_info_plus: ^9.0.0
  pasteboard: ^0.4.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  phone_numbers_parser: ^9.0.17
  phone_state: ^3.0.1
  photo_view: ^0.15.0
  pro_image_editor: ^11.14.0
  provider: ^6.1.5+1
  rive_animated_icon: ^2.0.5
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  sizer: ^3.1.3
  sliding_up_panel: ^2.0.0+1
  sqflite: ^2.4.2
  sticky_grouped_list: ^3.1.0
  substring_highlight: ^1.0.33
  timelines_plus: ^1.0.8
  translator: ^1.0.4+1
  url_launcher: ^6.3.2
  weather: ^3.2.1
  what3words: ^3.2.0
  whatsapp_unilink: ^2.1.0
  widgets_to_image: ^2.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  image_path: "assets/enrutador.png"
  adaptative_icon_background: "#000000FF"
  adaptative_icon_foreground: "assets/enrutador.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
